export const mockData: string[] = [
  'Christianity',
  'Islam',
  'Judaism',
  "Bahá'í Faith",
  'Druze',
  'Samaritanism',
  'Rastafarianism',
  'Hinduism',
  'Buddhism',
  'Jainism',
  'Sikhism',
  'Ayyavazhi',
  'Taoism',
  'Confucianism',
  'Shinto',
  'Mahayana Buddhism',
  'Shingon Buddhism',
  'Yoruba',
  'San',
  'Zulu Traditional Religion',
  'Ashanti Traditional Religion',
  'Dinka Traditional Religion',
  'Native American religions',
  'Australian Aboriginal spirituality',
  'Shamanism',
  'Inuit Traditional Religion',
  'Hmong Shamanism',
  'Scientology',
  'Raelism',
  'Wicca',
  'Paganism',
  'Falun Gong',
  'Ancient Egyptian religion',
  'Ancient Greek religion',
  'Ancient Roman religion',
  'Zoroastrianism',
  'Manichaeism',
  'Mithraism',
  'Deism',
  'Agnosticism',
  'Atheism',
  'Humanism',
  'Unitarian Universalism'
]
